In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import pymysql 
import math
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("Data/final_df.csv")

In [3]:
df.columns

Index(['Unnamed: 0', 'Order_Number', 'Order_Date', 'Customer_Names', 'Channel',
       'Product_Name', 'Order_Quantity', 'Unit_Price', 'Line_Total',
       'Total_Unit_Cost', 'State_Code', 'County', 'State', 'Region',
       'Latitude', 'Longitude', '2017_Budgets'],
      dtype='str')

In [4]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [5]:
df.head()

,Order_Number,Order_Date,Customer_Names,Channel,Product_Name,Order_Quantity,Unit_Price,Line_Total,Total_Unit_Cost,State_Code,County,State,Region,Latitude,Longitude,2017_Budgets
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,NaN
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,NaN
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,NaN
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,NaN
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,NaN

In [6]:
df.columns

Index(['Order_Number', 'Order_Date', 'Customer_Names', 'Channel',
       'Product_Name', 'Order_Quantity', 'Unit_Price', 'Line_Total',
       'Total_Unit_Cost', 'State_Code', 'County', 'State', 'Region',
       'Latitude', 'Longitude', '2017_Budgets'],
      dtype='str')

In [7]:
df["Line_Total"]

0        14994.6
1        25868.7
2         5869.2
3        16368.1
4        18331.2
          ...
64099    21788.4
64100     5185.8
64101    43483.0
64102    27717.9
64103     7986.4
Name: Line_Total, Length: 64104, dtype: float64

In [8]:
df["Total_Cost"] = df["Order_Quantity"] * df["Total_Unit_Cost"]

In [9]:
df["Profit"] = df["Line_Total"] - df["Total_Cost"]
df["Profit_Margit_Parcentage"] = df["Profit"] / df["Line_Total"]*100

In [10]:
df.head()

,Order_Number,Order_Date,Customer_Names,Channel,Product_Name,Order_Quantity,Unit_Price,Line_Total,Total_Unit_Cost,State_Code,County,State,Region,Latitude,Longitude,2017_Budgets,Total_Cost,Profit,Profit_Margit_Parcentage
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,NaN,10946.058,4048.542,27.0
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,NaN,13969.098,11899.602,46.0
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,NaN,4108.440,1760.760,30.0
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,NaN,7201.964,9166.136,56.0
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,NaN,10082.160,8249.040,45.0

### Exploratory Data Analyst

In [11]:
df.columns

Index(['Order_Number', 'Order_Date', 'Customer_Names', 'Channel',
       'Product_Name', 'Order_Quantity', 'Unit_Price', 'Line_Total',
       'Total_Unit_Cost', 'State_Code', 'County', 'State', 'Region',
       'Latitude', 'Longitude', '2017_Budgets', 'Total_Cost', 'Profit',
       'Profit_Margit_Parcentage'],
      dtype='str')

In [12]:
df.to_csv("Data/final_df.csv", index=False)